# Generated by Django 3.2.3 on 2021-05-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrier',
            fields=[
                ('id_barrier', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_barrier', models.CharField(max_length=255)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id_camera', models.BigAutoField(primary_key=True, serialize=False)),
                ('url_camera', models.CharField(max_length=255)),
                ('description', models.CharField(default=None, max_length=50)),
                ('id_barrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emegency.barrier', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id_car', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id_journal', models.BigAutoField(primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField()),
                ('id_camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emegency.camera', unique=True)),
                ('id_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emegency.cars', unique=True)),
            ],
        ),
    ]
