# Generated by Django 3.2.3 on 2021-06-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emegency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barrier',
            table='barrier',
        ),
        migrations.AlterModelTable(
            name='camera',
            table='camera',
        ),
        migrations.AlterModelTable(
            name='cars',
            table='cars',
        ),
        migrations.AlterModelTable(
            name='journal',
            table='journal',
        ),
    ]
