# Generated by Django 3.2.3 on 2021-06-02 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emegency', '0003_auto_20210602_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='id_barrier',
            field=models.ForeignKey(db_column='id_barrier', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emegency.barrier'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='id_camera',
            field=models.ForeignKey(db_column='id_camera', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emegency.camera'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='id_car',
            field=models.ForeignKey(db_column='id_car', null=True, on_delete=django.db.models.deletion.SET_NULL, to='emegency.cars'),
        ),
    ]
