# Generated by Django 3.2.3 on 2021-06-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emegency', '0004_auto_20210602_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id_timer', models.BigAutoField(primary_key=True, serialize=False)),
                ('barrier_timer', models.DurationField()),
                ('alert_timer', models.DurationField()),
            ],
            options={
                'db_table': 'timer',
            },
        ),
    ]
